import Head from "next/head";
import { Roboto } from "@next/font/google";

import RecordTable from "components/record/RecordTable";
import AddRecordForm from "components/record/AddRecordForm";

const roboto = Roboto({ weight: ["400", "700"], subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>NetPay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`flex flex-col items-center ${roboto.className}`}>
        <div className="my-10 flex">
          <AddRecordForm />
          <RecordTable />
        </div>
      </div>
    </>
  );
}
