import Head from "next/head";

import RecordTable from "components/record/RecordTable";
import AddRecordDialog from "components/record/AddRecordDialog";

export default function Home() {
  return (
    <>
      <Head>
        <title>NetPay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center">
        <div className="my-10">
          <AddRecordDialog />
          <RecordTable />
        </div>
      </div>
    </>
  );
}
